name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code
        run: |
          echo "Simulando despliegue..."
          # Aquí puedes agregar comandos como:
          # ssh user@your-server "cd /path/to/app && git pull origin development && pm2 restart app"
